--- #YAML:1.0
name:               WWW-Modbot
version:            0.01
abstract:           Tools to automoderate Web-based spam
author:
    - Michael Roberts <michael@despammed.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
